Repository ntut-xuan/FastShop, pull requests merged in 2022-09, with the labels that each got.

#2 Use application factory
  backend/README.md
  backend/app.py
  backend/tests/conftest.py
  backend/tests/test_factory.py
  requirements.txt
Labels: enhancement

#5 Use random secret key
  backend/app.py
Labels: security

#7 Add type check ci
  .github/workflows/type-check.yml
  backend/mypy.ini
Labels: enhancement

#12 Change describe on repository-root section and add docker-rebuild command.
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
Labels: documentation

#13 website navigation design
  backend/app.py
  html/index.html
  src/css/input.css
  src/jsx/index.jsx
  static/css/output.css
  static/image/advertisement.jpg
  static/image/fastshop.svg
  static/js/index.js
  tailwind.config.js
Labels: frontend, backend

#17 Fix script issues
  babel.sh
  tailwindcss.sh
Labels: bug

#20 Replace absolute path & use built-in static file serving
  backend/app.py
  backend/tests/test_factory.py
  backend/tests/test_static.py
  html/index.html
Labels: enhancement, backend

#22 Add unit test CI for backend
  .github/workflows/backend-unit-test.yml
  backend/tests/test_factory.py
Labels: enhancement, backend
